# GitHub Sponsors
github: [boi1duh]

# Patreon
# patreon: your-patreon-username

# Open Collective
# open_collective: switch-waste

# Ko-fi
# ko_fi: your-ko-fi-username

# Tidelift
# tidelift: npm/switch-waste-pro

# Community Bridge
# community_bridge: switch-waste

# Buy Me a Coffee
# buy_me_a_coffee: your-bmac-username

# Custom sponsorship URL
# custom: ['https://www.switchwaste.co.za/donate', 'https://www.paypal.me/switchwaste']